services:
  db-notifications:
    container_name: notifications_database
    image: mysql:8.4.1
    restart: always
    volumes:
      - notifications-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=notifications_db

volumes:
  notifications-mysql-data: